version: "3.8"

services:
  # Your Java App
  app:
    build: .
    image: take2018/xml-signer-app:0.1
    container_name: enbg-xml-signer
    ports:
      - "8080:8080"
    environment:
      ETS_IPS_SERVER_URL: http://192.168.20.45:9001
      ETS_IPS_CERTIFICATE_DOWNLOAD_URL: http://192.168.20.45:9001/v1/cert
      ETS_IPS_TOKEN_URL: http://192.168.20.45:9001/v1/token
      ETS_EPG_ACS_CERTIFICATE_ALIAS: ENBGETAA
      SECURITY_PKI_KEYSTORE_FILE_LOCATION: /config/keystore.jks
      SECURITY_PKI_KEYSTORE_FILE_STORE_PASSWORD: Test1@123
      SECURITY_PKI_KEYSTORE_FILE_KEY_PASSWORD: Test1@123
      SECURITY_PKI_KEYSTORE_TYPE: JKS
      SPRING_REDIS_HOST: redis          # <---- added for Redis connection
      SPRING_REDIS_PORT: 6379           # <---- Redis default port
      SPRING_REDIS_TIMETOLIVE: 1000
      HOME_LOG: /logs/
      POD_NAME: test_pod
      SPRING_PROFILES_ACTIVE: docker
      ETS_IPS_USERNAME: cbe
      ETS_IPS_PASSWORD: cbe1
      ETS_IPS_GRANTTYPE: password
      THREAD_COUNT: 5
      PARTICIPANT_BIC: ENBGETAA
    volumes:
      - /opt/ethswitch/keys/keystore.jks:/config/keystore.jks:ro
      - /var/log/logs/:/logs
    depends_on:
      - redis                          # <---- ensure app waits for Redis
    networks:
      - elk

  # Redis service
  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - elk
    volumes:
      - redis-data:/data               # <---- persistent storage

volumes:
  redis-data:

networks:
  elk:
    driver: bridge
