app:
  log:
    file:
      location: /var/log/app_ips.log
ets:
  epg:
    acs:
      certificate:
        alias: ets_acs
  ips:
    certificate:
      download:
        url: ${ets.ips.server.url}/v1/cert
    grantType: password
    password: CbE@IP$26_87
    server:
      url: http://172.31.6.117:32060
    token:
      url: ${ets.ips.server.url}/v1/token
    userName: commercialbankofethiopia
ips:
  participant:
    bic: CBETETAA
logging:
  level:
    httpclient:
      wire: INFO
    org:
      apache:
        http: INFO
      springframework:
        web: INFO
        web.client.RestTemplate: INFO
security:
  pki:
    keystore:
      file:
        key:
          password: wegagen123
        location: C:/etswitch/national_payment_gateway/certs/keys/participants/wegagen/keystore.p12
        store:
          password: wegagen123
      type: PKCS12
spring:
  redis:
    timeToLive: 1000