ets:
  epg:
    acs:
      certificate:
        alias: ${ETS_EPG_ACS_CERTIFICATE_ALIAS}
  ips:
    certificate:
      download:
        url: ${ETS_IPS_CERTIFICATE_DOWNLOAD_URL}
    grantType: ${ETS_IPS_GRANTTYPE}
    password: ${ETS_IPS_PASSWORD}
    server:
      url: ${ETS_IPS_SERVER_URL}
    token:
      url: ${ETS_IPS_TOKEN_URL}
    userName: ${ETS_IPS_USERNAME}

ips:
  participant:
    bic: ${PARTICIPANT_BIC}
  participants:
    -   bic: ENBGETAA
        grantType: password
        password: nbg
        refreshGrantType: refresh_token
        userName: nbg
logging:
  level:
    org:
      apache:
        http: INFO
      springframework:
        web: INFO
        web.client.RestTemplate: INFO

security:
  pki:
    keystore:
      file:
        key:
          password: ${SECURITY_PKI_KEYSTORE_FILE_KEY_PASSWORD}
        location: ${SECURITY_PKI_KEYSTORE_FILE_LOCATION}
        store:
          password: ${SECURITY_PKI_KEYSTORE_FILE_STORE_PASSWORD}
      type: ${SECURITY_PKI_KEYSTORE_TYPE}

spring:
  redis:
    host: ${SPRING_REDIS_HOST:redis}   # <---- default to 'redis' service inside Docker
    port: ${SPRING_REDIS_PORT:6379}    # <---- default Redis port
    password: ${SPRING_REDIS_PASSWORD:} # <---- optional, empty by default
    timeToLive: ${SPRING_REDIS_TIMETOLIVE:1000}
    timeout: 60000
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: 1000
        min-idle: 1

token:
  refresh:
    fixedDelay: 6000000000

retry:
  maxAttempts: 3
  delay: 2000

xml:
  signer:
    deployment:
      pod:
        name: ${POD_NAME}
    thread:
      count: ${THREAD_COUNT}
