ets:
  epg:
    acs:
      certificate:
        alias: ${ETS_EPG_ACS_CERTIFICATE_ALIAS}
  ips:
    certificate:
      download:
        url: ${ETS_IPS_CERTIFICATE_DOWNLOAD_URL}
    grantType: ${ETS_IPS_GRANTTYPE}
    password: ${ETS_IPS_PASSWORD}
    server:
      url: ${ETS_IPS_SERVER_URL}
    token:
      url: ${ETS_IPS_TOKEN_URL}
    userName: ${ETS_IPS_USERNAME}
ips:
  participant:
    bic: ${PARTICIPANT_BIC}
logging:
  level:
    org:
      apache:
        http: INFO
      springframework:
        web: INFO
        web.client.RestTemplate: INFO
security:
  pki:
    keystore:
      file:
        key:
          password: ${SECURITY_PKI_KEYSTORE_FILE_KEY_PASSWORD}
        location: ${SECURITY_PKI_KEYSTORE_FILE_LOCATION}
        store:
          password: ${SECURITY_PKI_KEYSTORE_FILE_STORE_PASSWORD}
      type: ${SECURITY_PKI_KEYSTORE_TYPE}
spring:
  redis:
    timeToLive: ${SPRING_REDIS_TIMETOLIVE}
xml:
  signer:
    deployment:
      pod:
        name: ${POD_NAME}
    thread:
      count: ${THREAD_COUNT}