app:
  log:
    file:
      location: /var/log/app_ips.log
ets:
  ips:
    certificate:
      download:
        url: ${ets.ips.server.url}/v1/cert
    grantType: password
    password: cbe1
    server:
      url: http://172.30.6.117:36487
    token:
      url: ${ets.ips.server.url}/v1/token
    userName: cbe
ips:
  participant:
    bic: CBETETAA
logging:
  level:
    httpclient:
      wire: INFO
    org:
      apache:
        http: INFO
      springframework:
        web: INFO
        web.client.RestTemplate: INFO
security:
  pki:
    keystore:
      file:
        key:
          password: wegagen123
        location: /opt/pki/Cert/keystore1.jks
        store:
          password: wegagen123
      type: JKS
spring:
  redis:
    timeToLive: 1000